In [5]:
from langchain_community.llms import Ollama
llm = Ollama(model="llama2")

In [7]:
llm.invoke(f"Describe this image. image :- {data}")

'\nLangsmith is a tool that can assist with testing by providing features such as:\n\n1. Syntax Highlighting: Langsmith can highlight the syntax of different programming languages, making it easier to identify and correct errors in code.\n2. Code Completion: Langsmith can provide code completion suggestions based on the context of the code, helping developers complete lines of code more quickly and accurately.\n3. Code Refactoring: Langsmith can help developers refactor their code by providing suggestions for improving its structure and organization, making it easier to understand and maintain.\n4. Debugging: Langsmith can assist with debugging by providing information about the state of the code during execution, helping developers identify and fix errors more quickly.\n5. Code Analysis: Langsmith can perform code analysis, identifying potential issues and suggesting improvements for code quality, readability, and maintainability.\n6. Integration with Other Tools: Langsmith can integr

In [7]:
import pandas as pd

# Assuming df is your DataFrame
# Replace df with the name of your DataFrame

# Create a DataFrame for demonstration
data = {'A': [0, 0, 1, 0],
        'B': [0, 0, 0, 0],
        'C': [0, 0, 0, 0]}
df = pd.DataFrame(data)

# Drop rows where all columns have value 0
mask = (df == 0).all(axis=1)
df = df[~mask]

print(df)


   A  B  C
2  1  0  0


In [10]:
from PyPDF2 import PdfReader 
reader = PdfReader('example.pdf') 
print(len(reader.pages)) 
page = reader
text = page
print(text)

1
Feb 1, 2024
Tirth Ajaykumar Patel
Probability & Statistics for Machine Learning &
Data Science
an online non-credit course authorized by DeepLearning.AI and offered through Courserahas successfully completed
Luis Serrano, Instructor, Serrano Academy. Anshuman Singh, Curriculum Product Manager, DeepLearning.AI. Elena
Sanina, Curriculum Engineer, DeepLearning.AI. Magdalena Bouza, Curriculum Developer, DeepLearning.AI. Obed Nsiah,
Curriculum Developer. Lucas Coutinho, Curriculum Developer, DeepLearning.AI
Verify at: 
https://coursera.org/verify/MXWV8ZDXDS7E   Coursera has confirmed the identity of this individual and their
participation in the course.


In [1]:
from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a worlds smartest. You know all the subject and its domain knowledge. You are given a pdf by the user, analyze the given pdf then you have to answer based on the questions asked by the user."),
    ("user", "Giving pdf as :- {pdf}, Questions as :- {questions}")
])

In [3]:
from langchain_community.llms import Ollama
llm = Ollama(model="llama2")

In [4]:
chain = prompt | llm 

In [19]:
from PyPDF2 import PdfReader 
reader = PdfReader('ex.pdf')
pdf = ""
for page_num in range(len(reader.pages)):
    page = reader.pages[page_num]
    text = page.extract_text()
    pdf += text

In [32]:
questions = "what is the machanism of action of ibuprofen?"

In [33]:
x = chain.invoke({"pdf": pdf, "questions": questions})

In [34]:
print(x)

Ibuprofen is a non-steroidal anti-inflammatory drug (NSAID) that works by inhibiting the production of prostaglandins, which are pro-inflammatory molecules that cause pain and inflammation. Ibuprofen specifically targets the cyclooxygenase (COX) enzymes, which are responsible for the synthesis of prostaglandins. By inhibiting COX, ibuprofen reduces the production of prostaglandins, leading to a decrease in pain and inflammation.

The mechanism of action of ibuprofen can be broken down into several steps:

1. Ibuprofen is absorbed into the bloodstream after oral administration.
2. Once in the bloodstream, ibuprofen is carried to the site of action, such as the inflamed area.
3. At the site of action, ibuprofen is converted to its active metabolite, which is then bound to the COX enzyme.
4. The active metabolite of ibuprofen inhibits the activity of COX, reducing the production of prostaglandins.
5. Prostaglandins are involved in the inflammatory response and cause pain by stimulating se

In [58]:
import PyPDF2

# Open the PDF file
pdf_file = open('ex.pdf', 'rb')

# Create a PDF reader object
pdf_reader = PyPDF2.PdfReader(pdf_file)
print("pdf_reader",pdf_reader)

# Get the number of pages in the PDF file
num_pages = len(pdf_reader.pages)
print("num_pages",num_pages)

# Get the first page
page = pdf_reader.pages[0]
print("pages",page)

xObject = page['/Resources']['/XObject'].get_object()  

for obj in xObject:
    # break
    if xObject[obj]['/Subtype'] == '/Image':
        size = (xObject[obj]['/Width'], xObject[obj]['/Height'])
        data = xObject[obj].get_data()
        print("data",data)
        if xObject[obj]['/ColorSpace'] == '/DeviceRGB':
            mode = "RGB"
        else:
            mode = "P"

        if xObject[obj]['/Filter'] == '/FlateDecode':
            img = open(f"image_{obj[1:]}.png", "wb")  
            img.write(data)
            img.close()
        elif xObject[obj]['/Filter'] == '/DCTDecode':
            img = open(f"image_{obj[1:]}.jpg", "wb")
            img.write(data)
            img.close()
        elif xObject[obj]['/Filter'] == '/JPXDecode':
            img = open(f"image_{obj[1:]}.jp2", "wb")
            img.write(data)
            img.close()

pdf_file.close()

pdf_reader <PyPDF2._reader.PdfReader object at 0x137f79550>
num_pages 282
pages {'/CropBox': [134, 179, 566, 827], '/MediaBox': [134, 179, 566, 827], '/Rotate': 0, '/Annots': IndirectObject(13877, 0, 5233939792), '/Resources': {'/ProcSet': ['/PDF', '/ImageC', '/Text', '/ImageB', '/ImageI'], '/XObject': {'/Im0': IndirectObject(8669, 0, 5233939792)}}, '/Parent': IndirectObject(8517, 0, 5233939792), '/Contents': IndirectObject(8625, 0, 5233939792), '/Type': '/Page'}
data b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00\x00d\x00d\x00\x00\xff\xe0\x00\x10JFIF\x00\x01\x02\x00\x00d\x00d\x00\x00\xff\xec\x00\x11Ducky\x00\x01\x00\x04\x00\x00\x00<\x00\x00\xff\xee\x00\x0eAdobe\x00d\xc0\x00\x00\x00\x01\xff\xdb\x00C\x00\x06\x04\x04\x04\x05\x04\x06\x05\x05\x06\t\x06\x05\x06\t\x0b\x08\x06\x06\x08\x0b\x0c\n\n\x0b\n\n\x0c\x10\x0c\x0c\x0c\x0c\x0c\x0c\x10\x0c\x0e\x0f\x10\x0f\x0e\x0c\x13\x13\x14\x14\x13\x13\x1c\x1b\x1b\x1b\x1c\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\xff\xdb\x00C\x01\x07\x07\x07\r\x0c\r\x18\x1

In [57]:
data

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00\x00d\x00d\x00\x00\xff\xe0\x00\x10JFIF\x00\x01\x02\x00\x00d\x00d\x00\x00\xff\xec\x00\x11Ducky\x00\x01\x00\x04\x00\x00\x00<\x00\x00\xff\xee\x00\x0eAdobe\x00d\xc0\x00\x00\x00\x01\xff\xdb\x00C\x00\x06\x04\x04\x04\x05\x04\x06\x05\x05\x06\t\x06\x05\x06\t\x0b\x08\x06\x06\x08\x0b\x0c\n\n\x0b\n\n\x0c\x10\x0c\x0c\x0c\x0c\x0c\x0c\x10\x0c\x0e\x0f\x10\x0f\x0e\x0c\x13\x13\x14\x14\x13\x13\x1c\x1b\x1b\x1b\x1c\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\xff\xdb\x00C\x01\x07\x07\x07\r\x0c\r\x18\x10\x10\x18\x1a\x15\x11\x15\x1a\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\xff\xc0\x00\x11\x08\x03\xee\x02\xbc\x03\x01\x11\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02

In [55]:
from langchain_community.llms import Ollama
llm = Ollama(model="llama2")
x = llm.invoke(f"Describe this image. image :- {data}")

'\nThe given string is a base64-encoded string. Here\'s the decoded version:\n```json\n{\n  "device_id": "7382e3a5290c4",\n  "model_name": "iPhone 11 Pro Max",\n  "operating_system": "ios",\n  "device_type": "smartphone",\n  "hardware_platform": "apple",\n  "device_manufacturer": "Apple Inc.",\n  "device_model": "A1503",\n  "device_os_version": "14.4",\n  "device_language": "en",\n  "device_timezone": "America/New_York",\n  "device_screen_resolution": "1080x2536",\n  "device_cpu_architecture": "ARM",\n  "device_os_version_major": 14,\n  "device_os_version_minor": 4,\n  "device_os_version_patch": 0,\n  "device_platform_name": "iOS"\n}\n```\nThe decoded string contains a JSON object with various device-related properties, such as the device ID, model name, operating system version, hardware platform, and more.'

In [59]:
!pip install --upgrade openai

  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
  Using cached tqdm-4.66.2-py3-none-any.whl.metadata (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.4/227.4 kB 2.8 MB/s eta 0:00:0000:010:01
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB 6.3 MB/s eta 0:00:00
Using cached tqdm-4.66.2-py3-none-any.whl (78 kB)


In [60]:
from openai import OpenAI
client = OpenAI(api_key="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")

completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."},
    {"role": "user", "content": "Compose a poem that explains the concept of recursion in programming."}
  ]
)

print(completion.choices[0].message)

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

In [20]:
import numpy as np

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b = np.array([[1],
              [2],
              [3],
              [4]])

c = np.zeros((3,4))

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] * b[j]

print(c)
print(a.shape)
print(b.T.shape)
print(a*b)


[[ 1.  4.  9. 16.]
 [ 5. 12. 21. 32.]
 [ 9. 20. 33. 48.]]
(3, 4)
(1, 4)


/var/folders/lb/37q51rqn7856y9wtxqn6w6580000gn/T/ipykernel_24469/2557857689.py:16: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  c[i][j] = a[i][j] * b[j]


ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [29]:
w =  np.array([[1.], [2]])
b = 1.5
X = np.array([[1., -2., -1.], [3., 0.5, -3.2]])
Y = np.array([[1, 1, 0]])
z = ((w)*X) + b
m = X.shape[1]
A = sigmoid((np.dot((w.T),X)) + b)
cost = -np.sum((Y*np.log(A))+((1-Y)*np.log(1-A)))/m
dw = -np.dot(X,((A-Y).T))/m
db = -np.sum(A-Y)/m

In [14]:
x = set()
x.add((1,2))
x

{(1, 2)}

In [26]:
from collections import defaultdict
dic = defaultdict(dict)
dic[(1,2)] = {"a": 1, "b": 4}
dic[(1,2)] 
dic[(1,4)] = {"a": 1, "b": 2}
dic

defaultdict(dict, {(1, 2): {'a': 1, 'b': 4}, (1, 4): {'a': 1, 'b': 2}})

In [34]:
neighbours = [(1,2), (2,3), (1,4), (4,2)]
mini = 1
path = defaultdict(dict)
path[1] = 0
for neighb,idx in neighbours:
    # if neighb == mini:
        # q.append(idx)
    path[neighb]
    path[idx] = path[neighb]
    del path[neighb]
path

defaultdict(dict, {3: 0, 2: {}})

In [47]:
if a==b:
    print("hello")
else:
    if c==d:
        print("world")

4
